<div id="linkbar">

	<div id="social">
		<div id="user-menu" class="menu">
		<ul>
			<li><a href="#"><img src="script/images/site/glider.png" border="0" >Opciones</a>
				<ul>
				<li><a href="#"><img id="icon-profile" src="script/images/site/profile.png" border=0>Ver Perfil</a></li>
				<li><a href="#"><img id="icon-stats" src="script/images/site/stats.png" border=0>Estadisticas</a></li>
				<li><a href="?accion=logoff"><img id="icon-logout" src="script/images/site/logout.png" border=0>Log Off</a></li>
				<li><?php ssi_logout(); ?></li>
				</ul>
			</li>
		</ul>
		</div>
	</div>
	<div id="opc-menu" class="menu">
		<ul>
			<li><a href="index.php" ><img id="icon-inicio" src="script/images/site/inicio.png" border=0>Inicio</a>|</li>
			<li><a href="#" ><img id="icon-cats" src="script/images/site/cats.png" border=0>Categorias</a>
				<ul>
				<li><a href="?accion=categoria&cat=cripto"><img id="icon-crypto" src="script/images/site/crypto.png" border=0>Criptografia</a></li>
				<li><a href="?accion=categoria&cat=estegano"><img id="icon-estegano" src="script/images/site/estegano.png" border=0>Esteganografia</a></li>
				<li><a href="?accion=categoria&cat=inversa"><img id="icon-inversa" src="script/images/site/inversa.png" border=0>Ing. Inversa</a></li>
				<li><a href="?accion=categoria&cat=web"><img id="icon-web" src="script/images/site/web.png" border=0>Web</a></li>
				<li><a href="?accion=categoria&cat=coding"><img id="icon-prog" src="script/images/site/programacion.png" border=0>Programacion</a></li>
				<li><a href="?accion=categoria&cat=misc"><img id="icon-misc" src="script/images/site/miscelanea.png" border=0>Miscelanea</a></li>
				</ul>
			</li>
			<li><a href="#" ><img id="icon-ranking" src="script/images/site/ranking.png" border=0>Ranking</a>|
				<ul>
				<li><a href="#"><img id="icon-user" src="script/images/site/profile.png" border=0>1. SmartGenius</a></li>
				<li><a href="#"><img id="icon-user" src="script/images/site/profile.png" border=0>2. John Cena</a></li>
				<li><a href="#"><img id="icon-user" src="script/images/site/profile.png" border=0>3. Albert Einstein</a></li>
				<li><a href="#"><img id="icon-user" src="script/images/site/profile.png" border=0>4. Will Smith</a></li>
				<li><a href="#"><img id="icon-user" src="script/images/site/profile.png" border=0>5. Jack Sparrow</a></li>
				<li></li>
				<li><a href="#"><img id="icon-user" src="script/images/site/ranking2.png" border=0>Ver todos</a></li>
				</ul>
			</li>
			<li><a href="../foro/index.php" ><img id="icon-comunity" src="script/images/site/comunidad.png" border=0>Comunidad</a>|</li>
			<li><a href="#" ><img id="icon-tools" src="script/images/site/tools.png" border=0>Herramientas</a>|
				<ul>
				<li><a href="#"><img id="icon-tools" src="script/images/site/tool1.png" border=0>Detector de Mentiras</a></li>
				<li><a href="#"><img id="icon-tools" src="script/images/site/tool2.png" border=0>Crackeador Universal</a></li>
				</ul>
			</li>

		</ul>
	</div>

	<div id="contact">
		<a href="contacto.php" rel="lyteframe" title="Contactanos" rev="width: 500px; height: 500px; scrolling: no;"><img src="script/images/site/contact.png" border="0" title="Contactanos"></a>
	</div>

</div>